name: CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: linux/amd64,linux/arm64
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Build multiplatform Docker image
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context:  ${{ github.workspace }}
          file:  ${{ github.workspace }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/saw303/unoserver-web:${{ github.ref_name }}
